server:
  port: 9129

spring:
  application:
    name: lclconfig-server
  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:h2db
#    username: root
#    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/lclconfig?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: lcl
    password: 123456
  sql:
    init:
      schema-locations: classpath:sql/db.sql
      mode: always
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true

logging:
  level:
    root: info


mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl