### list
GET http://localhost:9129/list?app=app1&env=dev&ns=public

### update
POST http://localhost:9129/update?app=app1&env=dev&ns=public
Content-Type: application/json

{
    "lcl.a": "dev33333",
    "lcl.c": "lcl400",
    "lcl.d": "lcl500"
}

### version
GET http://localhost:9129/version?app=app1&env=dev&ns=public



### demo 8888
GET http://localhost:8880/demo1



### update lclrpc config
POST http://localhost:9129/update?app=app1&env=dev&ns=public
Content-Type: application/json

{
  "lclrpc.provider.metas.dc": "sz",
  "lclrpc.provider.metas.gray": "false",
  "lclrpc.provider.metas.unit": "SZ001",
  "lclrpc.provider.metas.tc": 20
}

### get status 9129
GET http://localhost:9129/status

### get status 9130
GET http://localhost:9130/status

### get status 9131
GET http://localhost:9131/status